### ISSUE TITLE
前端 CSS 规范

### ISSUE THREAD

**Issue by mason369** [School-of-Website-Engineering/Heimatoutiao#3]
# 前端 CSS 规范

## 分号

每个属性声明后面都要加分号。

## 命名

1. 不使用 id 选择器
2. 适用有意义的名词命名
3. 单词全部小写，名词超过 1 个时，使用-分隔符

## 属性声明顺序

原则：整体到局部，外部到内部，重要属性优先

```css
.element {
	display: block;
	float: left;
	position: absolute;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
	z-index: 100;
	margin: 0 100px;
	padding: 50px; // padding习惯写到margin后面
	width: 100px;
	height: 100px;
	border: 1px solid #e5e5e5;
	border-radius: 3px;
	font: normal 13px "Helvetica Neue", sans-serif;
	color: #333;
	text-align: center;
	line-height: 1.5;
	background-color: #f5f5f5;
	opacity: 1;
}
```

## 参考连接

[百度 CSS 规范指南(opens new window)](https://github.com/ecomfe/spec/blob/master/css-style-guide.md)

[腾讯 CSS 规范指南(opens new window)](http://alloyteam.github.io/CodeGuide/#css)

[Google CSS 规范指南](http://iischajn.github.io/trans/htmlcss-guide/)
